spring:
  mvc:
    view:
      prefix: /
      suffix: .html
  datasource:
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8&useSSL=false&allowMultiQueries=true
    username: root
    password: Wangjikai159
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    show-sql: false
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
    open-in-view: true
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: novel
  thymeleaf:
    cache: false
server:
  port: 80